version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: kairos-postgres
    environment:
      POSTGRES_DB: kairos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kairos_network

  # Redis for Rate Limiting
  redis:
    image: redis:7-alpine
    container_name: kairos-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kairos_network

  # Kairos Fitness Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kairos-app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres_password@postgres:5432/kairos_db
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-here
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/app/uploads
    networks:
      - kairos_network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: kairos-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - kairos_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  kairos_network:
    driver: bridge